# Meta Data for SEO

## Homepage
title = "DBA Dash"
titleSeparator = "-"
titleAddition = "SQL Server Monitoring"
description = "DBA Dash is a tool for SQL Server DBAs to assist with daily checks, performance monitoring and tracking configuration changes."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["DBADash_Performance_small.png"]
ogLocale = "en_US"
domainTLD = "dbadash.com"
titleHome = "DBA Dash"

## Twitter Cards
twitterSite = "@wiseDATAman"
twitterCreator = "@wiseDATAman"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "DBA Dash"
schemaAuthor = "David Wiseman"
schemaAuthorTwitter = "https://twitter.com/wiseDATAman"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/wisedataman/"
schemaAuthorGitHub = "https://github.com/DavidWiseman"
schemaLocale = "en-US"
schemaLogo = "DBADash_Performance_small.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "DBADash_Performance_small.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/wiseDATAman"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/trimble-oss/dba-dash"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "16000"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Created by <a  class=\"text-muted\" href=\"https://github.com/DavidWiseman\">David Wiseman</a>, <a  class=\"text-muted\" href=\"https://www.trimble.com\">Copyright Â© 2022 Trimble, Inc</a>"

# Feed
copyRight = "Copyright (c) 2022 Trimble, Inc"

# Alert
alert = false
alertDismissable = true
alertText = "Add alert text here"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/DavidWiseman/dba-dash-docs"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
